### ISSUE TITLE
Should be configurable with a config file

### ISSUE THREAD

**Issue by quartercastle** [upsub/dispatcher#18]
- Should be toml or yml, look at this [library](https://github.com/go-yaml/yaml).
- Should be able to hot reload the config
- Webhooks should be managed in the config, resolves #26.

**Comment by quartercastle** [comment]
```yaml
# /etc/upsub/config.yml
port: 4400
max-message-size: 512000
connection-timeout: 30
read-timeout: 30
write-timeout: 30

nats:
  host: localhost
  port: 4222

hooks:
  channel/event: 
    - http://service.com/hook
```

**Comment by quartercastle** [comment]
```toml
port = 4400
max-message-size = 512000
connection-timeout = 30
read-timeout = 30
write-timeout = 30

[nats]
host = "localhost"
port = 4222

[hooks]
"channel/event" = ["http://service.com/hook"]
```
