### ISSUE TITLE
Implement Auth, create, update and delete functionality

### ISSUE THREAD

**Issue by quartercastle** [upsub/dispatcher#22]
- Root auth should default have rules which allows it to create, update and delete auths.
- Other auths can be allowed to create, update and delete but only in their own scope.
- Should not be available if the connection is established from a browser.
- Auth messages should flow on the channel `upsub/auth/>`, this channel is only available in the auth scope and isn't available for parent auths.

**Comment by quartercastle** [comment]
```js
// upsub/auth/create
{
	id: 'string',
	secret: 'string',
	public: 'string',
	origins: ['string'],
	rules: {
		create: false,
		update: false,
		delete: false
	}
}
```

**Comment by quartercastle** [comment]
```js
// upsub/auth/update
{
	id: 'string',
	secret: 'string',
	public: 'string',
	origins: ['string'],
	rules: {
		create: false,
		update: false,
		delete: false
	}
}
```

**Comment by quartercastle** [comment]
```js
// upsub/auth/delete
'id'
```

**Comment by kvartborg** [comment]
```yml
# Example of a yml config containing the auths
auths:
  app-id: root
  secret: root-secret
  public: ''
  origins: []
  auths:
    app-id: upsub-gui
    secret: 41588877cdc5d7760e34035a915e
    public: db5ab76dd675168041a46c29cd43
    origins: [https://upsub.io]
```
